version: '3.3'

services:
  api:
    build: ./
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5439:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=snv
  #     - POSTGRES_HOST=localhost