# Generated by Django 4.0 on 2022-04-02 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_album_gallery_alter_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='gallary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
            preserve_default=False,
        ),
    ]
