# Generated by Django 4.0 on 2022-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_gallary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='gallary',
            new_name='gallery',
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(to='gallery.Image'),
        ),
    ]
