# Generated by Django 4.0 on 2022-03-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='document')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='document')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='document')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_code')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='accounts.user')),
            ],
        ),
    ]
