# Generated by Django 4.0 on 2022-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_verification_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
